Fix: добавила переходы по кликам
agricultural-machinery-rental/client pull request #69
Opened 2023-08-16 08:55 UTC by Lakatosska

1. Was done:
   - [x] Текущие заявки – редактирование – Клик на карандаш, чтобы открывалась модалка редактирования бронирования
   - [x] CallbackSuccess – переход на главную, закрытие модалки
   - [x] На главной странице кликаем на красивые картинки – переход на страницу Каталог

2023-08-16 09:02 UTC, mrHoft approved these changes

2023-08-16 09:02 UTC, mrHoft commented on src/widgets/company/Callback/CallbackSucces/ui.tsx
> +      </Link>
Зачем кнопку оборачивать в Link да ещё и с разными с ней событиями?

2023-08-16 09:58 UTC, Lakatosska commented on src/widgets/company/Callback/CallbackSucces/ui.tsx
> +      </Link>
да, ты прав. поправила. и еще в паре мест)

2023-08-16 16:30 UTC, djpont requested changes

2023-08-16 16:30 UTC, djpont commented on src/widgets/company/Callback/CallbackSucces/ui.tsx
> +    router.push('/');
```suggestion
    router.push(PATH.MainPage);
```

2023-08-16 16:30 UTC, djpont commented on src/widgets/company/Callback/CallbackSucces/ui.tsx
> +    router.push('/');
Импорт из src/shared/constants/path.ts

2023-08-16 16:30 UTC, djpont commented on src/widgets/user/Booking/BookingCancelSuccess/ui.tsx
> +    router.push('/');
```suggestion
    router.push(PATH.MainPage);
```

2023-08-16 16:30 UTC, djpont commented on src/widgets/user/Booking/BookingSuccess/ui.tsx
> +    router.push('/');
```suggestion
    router.push(PATH.MainPage);
```

2023-08-18 05:44 UTC, Catalinadevolg approved these changes
Почти всё переделать пришлось после моего PR (
Спасибо за хорошую работу!

2023-08-18 09:24 UTC, djpont approved these changes

2023-08-18 09:53 UTC, merged