Feat/005 UI
agricultural-machinery-rental/client pull request #8
Opened 2023-07-24 15:53 UTC by Lakatosska

2023-07-24 19:34 UTC, djpont commented on src/components/UI/Button/Button.tsx
> +}) => {
Т.к. у кнопки есть тип TButton, то лучше в параметрах принимать props, а уже ниже в коде делать деструктуризацию
```js
const {
  label,
  designType = 'primary',
  shape = 'round',
  sizeType = 'middle'
} = props;
```

2023-07-24 19:34 UTC, djpont commented on src/components/UI/Button/styled.ts
> +  margin: 0;
Можно, кстати, в globals добавить 
```css
* {
  padding: 0;
  margin: 0;
}
```
Чтобы у всего сбросить отступы, а потом уже в компонентах указывать их, если требуется по дизайну.

2023-07-24 19:34 UTC, djpont commented on src/components/UI/Button/styled.ts
> +      : '';
Не уверен, что этот код работает. Лучше через switch case сделать
```js
switch(sizeType){
  'small':
    return theme.sizesHeight.small;
  'middle':
    return theme.sizesHeight.middle;
  default:
    return theme.sizesHeight.large;
}
```

2023-07-24 19:34 UTC, djpont commented on src/components/UI/Button/typing.ts
> +  designType?: 'primary' | 'secondary';
Ниже есть DesignType, лучше его использовать, чтобы в местах, где нужно указать designType, то брать его как DesignType.primary, например.
Но можно и так оставить, зафиксировать тип как конкретные строки. Нужно определиться с нами кодстилем.

2023-07-24 19:34 UTC, djpont commented on src/components/UI/Input/Input.tsx
> +}) => {
тут тоже деструктуризацию лучше делать

2023-07-24 19:34 UTC, djpont commented on src/components/UI/Input/typing.ts
> +export interface InputProps extends InputHTMLAttributes<HTMLInputElement> {
Мы решили использовать типы.

2023-07-24 19:34 UTC, djpont commented on src/styles/theme.ts
> +export const theme = {
Мне нравится как типы вынесены

2023-07-25 06:03 UTC, Catalinadevolg commented on src/components/UI/Button/Button.tsx
> +}) => {
Не согласна. Чем лучше?

2023-07-25 07:23 UTC, Catalinadevolg requested changes

2023-07-25 07:23 UTC, Catalinadevolg commented on src/styles/theme.ts
> +    white: '#ffffff',
Если это окончательные стили из фигмы, то тут primary и white повторяются. Если primary ещё не окончательно определён, я бы оставила TODO, а то потом можем забыть об этом.

2023-07-25 07:23 UTC, Catalinadevolg commented on src/components/UI/Button/Button.tsx
> +    >
В пропсах есть icon и он передается в стилизованный компонент. Не вижу, что с ним происходит дальше.

2023-07-25 07:23 UTC, Catalinadevolg commented on src/components/UI/Button/Button.tsx
> +      onClick={handleClick}
Тут видимо нужно убрать `onClick={handleClick}`
т.к. в пропсах приходит `onClick`

2023-07-25 07:23 UTC, Catalinadevolg commented on src/components/UI/Button/Button.tsx
> +      //sizeType={sizeType}
А почему sizeType закомментирован?

2023-07-25 07:23 UTC, Catalinadevolg commented on src/components/UI/Input/Input.tsx
> +    ...(required && { required: 'Поле не может быть пустым' }),
Это нужно будет, если мы будет использовать react-hook-form. Не обсуждали пока что для форм будем использовать

2023-07-25 07:23 UTC, Catalinadevolg commented on src/components/UI/Input/Input.tsx
> +      {error && <StError>{errorMessage}</StError>}
На самом деле не вижу смысла добавлять пропс error и делать проверку есть он или нет. Как мне видится, `errorMessage` достаточно. Если `errorMessage` есть, то и выводим `StError`.

2023-07-25 07:23 UTC, Catalinadevolg commented on src/components/UI/Input/styled.ts
> +  height: 3.1em;
Почему здесь решила поставить em?

2023-07-25 07:23 UTC, Catalinadevolg commented on src/components/UI/Input/styled.ts
> +
А есть ли смысл делать стилизованный контейнер? Пока из этих свойств не вижу что нужно именно в контейнере. Бордер у инпута можно указать. А класса `profile_input` у нас пока нет. В проекте с игрой мы его использовали, потому что в формах регистрации/логина и в профиле text-align был разный. По прототипам у нас во всех формах выравнивание текста одинаковое.

2023-07-25 07:23 UTC, Catalinadevolg commented on src/components/UI/Input/styled.ts
> +  border: 0;
Эти свойства и `outline` нужно в обнуляющие стили вынести (возможно Саша их уже добавил)

2023-07-25 07:23 UTC, Catalinadevolg commented on src/components/UI/Input/Input.tsx
> +      <StLabel htmlFor={name}>{label}</StLabel>
Вообще по прототипам я не вижу у нас лейбла. Там будто только placeholder'ы отображаются. Нужен ли он нам с такими стилями?

2023-07-25 07:23 UTC, Catalinadevolg commented on src/components/UI/Input/styled.ts
> +  padding: 10px 20px 0;
Внутренние отступы у нас `16px 8px`

2023-07-25 07:23 UTC, Catalinadevolg commented on src/components/UI/Input/styled.ts
> +  padding: 5px;
Отступ ошибки сверху (от инпута) 8px, от левого края ещё больше.

2023-07-25 07:27 UTC, Catalinadevolg commented on src/components/UI/Input/styled.ts
> +
Бордер даже нужно указать у инпута, иначе, если добавится ошибка, то бордер будет и вокруг этой ошибки

2023-07-25 12:02 UTC, djpont commented on src/components/UI/Button/Button.tsx
> +}) => {
Теперь я тоже не согласен, почитал "лучшие практики" на хабре и там оба варианта используются.

2023-07-25 12:08 UTC, djpont commented on src/components/UI/Input/Input.tsx
> +        className={className}
className уже есть в props, можно тут убрать и выше, в параметрах функции, тоже убрать.

2023-07-26 08:17 UTC, Catalinadevolg approved these changes

2023-07-26 08:23 UTC, merged